
spring:
  data:
    mongodb:
      database: bdclients
      uri: mongodb+srv://user_mongo:G1TFNZUPitWXoy8z@cluster0.7dn2n.mongodb.net/bdclients?retryWrites=true&w=majority
      repositories:
        type: auto
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
##mongodb://localhost:27017
##mongodb+srv://user_mongo:<password>@cluster0.7dn2n.mongodb.net/<dbname>?retryWrites=true&w=majority

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka